groups/urls.py
from django.urls import path

from .views import CreateGroupView
from .views import DeleteGroupView
from .views import ListGroupView
from .views import UpdateGroupView

# CRUD - Create, Read, Update, Delete

app_name = 'groups'

urlpatterns = [
    path('', ListGroupView.as_view(), name='list'),                              # Read
    path('create/', CreateGroupView.as_view(), name='create'),                   # Create
    path('update/<int:pk>/', UpdateGroupView.as_view(), name='update'),          # Update
    path('delete/<int:pk>/', DeleteGroupView.as_view(), name='delete'),          # Delete
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# http://   localhost:8080/     students/       create/

groups/models.py
import datetime

from django.db import models

from teachers.models import Teacher


class Group(models.Model):
    name = models.CharField(max_length=50)
    start_date = models.DateField(default=datetime.date.today)
    end_date = models.DateField(null=True)
    headman = models.OneToOneField(
        'students.Student',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='headman_group'
    )
    teachers = models.ManyToManyField(
        to=Teacher,
        blank=True,
        related_name='groups'
    )
    create_datetime = models.DateTimeField(auto_now_add=True)
    update_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'groups'

    def __str__(self):
        return self.name

groups/forms.py
from django import forms

from .models import Group


class GroupBaseForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        # [
        #     'name',
        #     'start_date',
        #     'end_date'
        # ]

        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'})
        }


class GroupUpdateForm(GroupBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['headman_field'] = forms.ChoiceField(
            choices=[
                (student.pk, f'{student.first_name} {student.last_name}') for student in self.instance.students.all()
            ],
            label='Headman',
            required=False
        )

    class Meta(GroupBaseForm.Meta):
        exclude = ['start_date', 'headman']


class GroupCreateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        exclude = ['end_date', 'headman']

groups/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import UpdateView

from students.models import Student

from .forms import GroupCreateForm
from .forms import GroupUpdateForm
from .models import Group


class CreateGroupView(CreateView):
    model = Group
    form_class = GroupCreateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/create.html'


class DeleteGroupView(DeleteView):
    model = Group
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/delete.html'


class ListGroupView(ListView):
    model = Group
    template_name = 'groups/list.html'


class UpdateGroupView(UpdateView):
    model = Group
    success_url = reverse_lazy('groups:list')
    form_class = GroupUpdateForm
    template_name = 'groups/update.html'

    # extra_context = {'group': group}
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.prefetch_related('headman_group')

        return context

    def get_initial(self):
        initial = super().get_initial()
        try:
            initial['headman_field'] = self.object.headman.pk
        except AttributeError:
            pass

        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        try:
            form.instance.headman = Student.objects.get(pk=form.cleaned_data['headman_field'])
            form.instance.save()
        except ValueError:
            pass

        return response

groups/templates/groups/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create group{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>
        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Create">
            <a class="btn btn-success" href="{% url 'groups:list' %}">Cancel</a>
        </div>
    </form>
{% endblock %}

groups/templates/groups/delete.html
{% extends 'base.html' %}

{% block title %}Delete group{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove
            <span style="font-style: italic; font-weight: bold;">
                {{ object.name }}
            </span>?
        </p>
        <div class="mt-2">
            <input class="btn btn-outline-danger" type="submit" value="Agree">
            <a class="btn btn-outline-primary" href="{% url 'groups:list' %}">Cancel</a>
        </div>
    </form>
{% endblock %}

groups/templates/groups/list.html
{% extends 'base.html' %}

{% block title %}List of groups{% endblock %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <th>N</th>
            <th>Name</th>
            <th>Headman</th>
            <th>Start date</th>
            <th>End date</th>
            <th><i class="bi bi-pencil-fill"></i></th>
            <th><i class="bi bi-trash-fill"></i></th>
        </tr>
        {% for group in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ group.name }}</td>
            <td>{{ group.headman.last_name }} {{ group.headman.first_name }}</td>
            <td>{{ group.start_date }}</td>
            <td>{% if group.end_date %}{{ group.end_date }}{% endif %}</td>
            <td><a href="{% url 'groups:update' group.pk %}">Update</a></td>
            <td><a href="{% url 'groups:delete' group.pk %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

groups/templates/groups/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update group{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success mt-3" type="submit">Update</button>
        <a class="btn btn-primary mt-3" href="{% url 'groups:list' %}">Cancel</a>
    </form>
    {% with list_object=students on_group=False %}
        {% include 'includes/students_list_table.html' %}
    {% endwith %}
{% endblock %}