accounts/urls.py
from django.urls import path

from .views import AccountLoginView
from .views import AccountLogoutView
from .views import AccountRegistrationView
from .views import AccountUpdateView
from .views import account_view

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_view, name='profile_view'),
    path('update/', AccountUpdateView.as_view(), name='profile_update'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# http://   localhost:8080/     students/       create/

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/', default='default.png')

    class Meta:
        db_table = 'profile'

    def __str__(self):
        return ''


@receiver(post_save, sender=User)
def create_new_profile(sender, instance, created, **kwargs):
    if created:
        p = Profile(user=instance)
        p.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm

from .models import Profile


class UserRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm.Meta):
        fields = [
            'first_name',
            'last_name',
            'email',
        ]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'birthday',
            'city',
            'avatar',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView

from .forms import ProfileUpdateForm
from .forms import UserRegistrationForm
from .forms import UserUpdateForm


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('index')
    form_class = UserRegistrationForm


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'

    def get_redirect_url(self):
        next_value = self.request.GET.get('next')
        if next_value:
            return next_value

        return reverse('index')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'User <{self.request.user}> has successfully logged in.')
        # messages.warning(self.request, f'User <{self.request.user}> has successfully logged in.')
        # messages.error(self.request, f'User <{self.request.user}> has successfully logged in.')

        return response


class AccountLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/logout.html'


class AccountUpdateView(LoginRequiredMixin, ProcessFormView):
    def get(self, request, *args, **kwargs):
        user = request.user
        profile = request.user.profile
        user_form = UserUpdateForm(instance=user)
        profile_form = ProfileUpdateForm(instance=profile)

        return render(request, 'accounts/update.html', {'user_form': user_form, 'profile_form': profile_form})

    def post(self, request, *args, **kwargs):
        user = self.request.user
        profile = user.profile
        user_form = UserUpdateForm(instance=user, data=request.POST)
        profile_form = ProfileUpdateForm(instance=profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('accounts:profile_view'))

        return render(request, 'accounts/update.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def account_view(request):
    return render(request, 'accounts/profile.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Login{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <a href="{% url 'password_reset' %}">If you forgot password!</a>
        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Login">
            <a class="btn btn-success" href="{% url 'accounts:registration' %}">Registration</a>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
    <a class="btn btn-success" href="{% url 'accounts:login' %}">Login</a>
    <a class="btn btn-success" href="{% url 'accounts:registration' %}">Registration</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}User profile{% endblock %}

{% block content %}
    <div>
        <div class="col-md-4">
              <img src="{{ user.profile.avatar.url }}" class="rounded-circle p-3" width="200" height="200" alt="avatar">
        </div>
        <div class="p-3 m-3">
            <h2 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><span class="h5">Username:</span> {{ user.username }}</li>
        <li class="list-group-item">
            <span class="h5">Birthday: </span>
            {% if user.profile.birthday %}{{ user.profile.birthday }}{% endif %}
        </li>
        <li class="list-group-item">
            <span class="h5">City: </span>
            {% if user.profile.city %}{{ user.profile.city }}{% endif %}
        </li>
    </ul>
    <div class="mt-3">
        <a class="btn btn-success" href="{% url 'accounts:profile_update' %}">Change profile</a>
        <a class="btn btn-danger" href="{% url 'password_change' %}">Change password</a>
    </div>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create account{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Registration">
            <a class="btn btn-success" href="{% url 'accounts:login' %}">Login</a>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Edit profile{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <div class="col-md-4">
              <img src="{{ user.profile.avatar.url }}" class="rounded-circle p-3" width="200" height="200" alt="avatar">
            </div>
            <div class="p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        {{ user_form | crispy }}
        {{ profile_form | crispy }}
        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Update">
            <a class="btn btn-success" href="{% url 'accounts:profile_view' %}">Cancel</a>
        </div>
    </form>
{% endblock %}