accounts/urls.py
from django.urls import path

from .views import AccountLoginView
from .views import AccountLogoutView
from .views import AccountRegistrationView
from .views import AccountUpdateView
from .views import account_view

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_view, name='profile_view'),
    path('update/', AccountUpdateView.as_view(), name='profile_update'),
]

groups/urls.py
from django.urls import path

from .views import CreateGroupView
from .views import DeleteGroupView
from .views import ListGroupView
from .views import UpdateGroupView

# CRUD - Create, Read, Update, Delete

app_name = 'groups'

urlpatterns = [
    path('', ListGroupView.as_view(), name='list'),                              # Read
    path('create/', CreateGroupView.as_view(), name='create'),                   # Create
    path('update/<int:pk>/', UpdateGroupView.as_view(), name='update'),          # Update
    path('delete/<int:pk>/', DeleteGroupView.as_view(), name='delete'),          # Delete
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# http://   localhost:8080/     students/       create/

students/urls.py
from django.urls import path

from .views import ListStudentView
from .views import UpdateStudentView
from .views import create_student
from .views import delete_student

# CRUD - Create, Read, Update, Delete

app_name = 'students'

urlpatterns = [
    path('', ListStudentView.as_view(), name='list'),                              # Read
    path('create/', create_student, name='create'),                   # Create
    path('update/<int:identity>/', UpdateStudentView.as_view(), name='update'),          # Update
    path('delete/<int:pk>/', delete_student, name='delete'),          # Delete
]

templates/includes/menu.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg mb-2" style="background-color: #e3f2fd;">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="{% static 'img/logo.png' %}" alt="" width="30" height="24">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Students
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'students:list' %}">List</a></li>
                        <li><a class="dropdown-item" href="{% url 'students:create' %}">Create</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Groups
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'groups:list' %}">List</a></li>
                        <li><a class="dropdown-item" href="{% url 'groups:create' %}">Create</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about/">About</a>
                </li>
            </ul>
            {#      <form class="d-flex" role="search">#}
            {#        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
            {#        <button class="btn btn-outline-success" type="submit">Search</button>#}
            {#      </form>#}
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="student-dropdown"
                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="student-dropdown">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item"
                                       href="{% url 'accounts:profile_view' %}">Profile</a></li>
                                <li><a class="dropdown-item"
                                       href="{% url 'password_change' %}">Change password</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item"
                                       href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a class="dropdown-item"
                                       href="{% url 'accounts:login' %}">Login</a></li>
                                <li><a class="dropdown-item"
                                       href="{% url 'accounts:registration' %}">Registration</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/paginator.html
<nav aria-label="paginator">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1{{ params }}"><i class="bi bi-chevron-double-left"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ params }}"><i class="bi bi-chevron-left"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-left"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-left"></i></a></li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
                <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>
            {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}{{ params }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ params }}"><i class="bi bi-chevron-right"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{ params }}"><i class="bi bi-chevron-double-right"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-right"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-right"></i></a></li>
        {% endif %}
    </ul>
</nav>

templates/includes/students_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th style="width: 5%">N</th>
            <th style="width: 20%">First name</th>
            <th style="width: 20%">Last name</th>
            <th style="width: 5%">Age</th>
{#            <th style="width: 15%">Birthday</th>#}
            <th><i class="bi bi-telephone-fill"></i></th>
            {% if on_group %}<th style="width: 10%">Group</th>{% endif %}
            <th>Headman</th>
            {% if user.is_authenticated %}
                <th style="width: 5%"><i class="bi bi-pencil-fill"></i></th>
                <th style="width: 5%"><i class="bi bi-trash3-fill"></i></th>
            {% endif %}
        </tr>
    </thead>
    {% for student in list_object %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{% if student.get_age %}{{ student.get_age }}{% endif %}</td>
{#            <td>{{ student.birthday }}</td>#}
            <td>{% if student.phone_number %}{{ student.phone_number }}{% endif %}</td>
            {% if on_group %}
                <td>{% if student.group %}{{ student.group }}{% endif %}</td>
            {% endif %}
            <td>{% if student.headman_group %}<i class="bi bi-check-circle-fill"></i>{% endif %}</td>
            {% if user.is_authenticated %}
                <td><a href="{% url 'students:update' student.pk %}">Edit</a></td>
                <td><a href="{% url 'students:delete' student.pk %}">Delete</a></td>
            {% endif %}
        </tr>
    {% endfor %}
</table>